In [1]:
import pandas as pd
import pickle
import os
from sklearn.model_selection import train_test_split

In [ ]:
# Task1: get data from data folder
ratings = pd.read_csv("../data/ml-20m/ratings.csv")
movies = pd.read_csv("../data/ml-20m/movies.csv")
ratings = ratings.drop(columns=["timestamp"])
display(movies.head(100))

display(ratings.head(100))

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
95,97,"Hate (Haine, La) (1995)",Crime|Drama
96,98,Shopping (1994),Action|Thriller
97,99,Heidi Fleiss: Hollywood Madam (1995),Documentary
98,100,City Hall (1996),Drama|Thriller
99,101,Bottle Rocket (1996),Adventure|Comedy|Crime|Romance

    userId  movieId  rating
0        1        2     3.5
1        1       29     3.5
2        1       32     3.5
3        1       47     3.5
4        1       50     3.5
..     ...      ...     ...
95       1     2947     3.5
96       1     2959     4.0
97       1     2968     4.0
98       1     3000     3.5
99       1     3030     3.0

[100 rows x 3 columns]

In [3]:
print("Ratings shape:",ratings.shape)
print("MOvies shape:",movies.shape)

print("unique users:",ratings["userId"].unique())
print("Unique rated movies:",ratings["movieId"].unique())

print("\nRating min:",ratings.min())
print("\nRating max:",ratings.max())

print("\nMissing Values in Ratings:",ratings.isnull().sum())
print("\nMissing Values in Movies",movies.isnull().sum())

Ratings shape: (20000263, 3)
MOvies shape: (27278, 3)
unique users: [     1      2      3 ... 138491 138492 138493]
Unique rated movies: [     2     29     32 ... 121021 110167 110510]

Rating min: userId     1.0
movieId    1.0
rating     0.5
dtype: float64

Rating max: userId     138493.0
movieId    131262.0
rating          5.0
dtype: float64

Missing Values in Ratings: userId     0
movieId    0
rating     0
dtype: int64

Missing Values in Movies movieId    0
title      0
genres     0
dtype: int64

In [ ]:
# Task3: Encode userId and movieId
user_ids = ratings["userId"].unique()
movie_ids = ratings["movieId"].unique()

user2idx = {}
for idx,uid in enumerate(user_ids):
    user2idx[uid] = idx

movie2idx = {}
for idx,mid in enumerate(movie_ids):
    movie2idx[mid] = idx

ratings["user"] = ratings["userId"].map(user2idx)
ratings["movie"] = ratings["movieId"].map(movie2idx)
ratings["rating_norm"] = ratings["rating"]/5.0

num_users = len(user2idx)
num_movies = len(movie2idx)

print(f"Users:{num_users}")
print(f"Movies:{num_movies}")
print(f"Ratings:{len(ratings):,}")
print("Splitting Data..............................")

Users:138493
Movies:26744
Ratings:20,000,263
Splitting Data..............................

In [ ]:
#Task 4: Train/Test Split

train,test = train_test_split(
    ratings,
    test_size=0.2,
    random_state=32
)

os.makedirs("../data",exist_ok=True)
train.to_csv("../data/train.csv",index=False)
test.to_csv("../data/test.csv",index=False)

In [ ]:
#Task view the created test/train csv
test =pd.read_csv("../data/test.csv") 
train =pd.read_csv("../data/train.csv") 

display(test.head(20))
display(train.head(20))

## Task 5: Save Encoders

In [8]:
with open("../data/encoders.pkl","wb") as f:
    pickle.dump({
        "user2idx":user2idx,
        "movie2idx":movie2idx,
        "num_users":num_users,
        "num_movies":num_movies
    },f)

## Task 6: Create movies_encoded.csv

In [9]:
movies["movieId_enc"] = movies["movieId"].map(movie2idx)
movies = movies.dropna(subset=["movieId_enc"])
movies["movieId_enc"] = movies["movieId_enc"].astype(int)
movies.to_csv("../data/movies_encoded.csv",index=False)

In [ ]:
print("Preprocessing Complete.")
print("Saved train.csv, test.csv, encoders.pkl, movies_encoded.csv")